### ISSUE TITLE
RocketChat NPC Discussion

### ISSUE THREAD

**Issue by yufansong** [TheAgentCompany/TheAgentCompany#105]
Discussed with @XuhuiZhou  and @frankxu2004 , here is some conclusion
TODO:
- [x] Define the NPC information in profile #112
- [x] Insert the NPC information in Redis #106
- [x] NPC rocketchat username and password should be global #107
- [x] Doc instruction: each task should have customized senoria.json #108
- [x] Create json to list multiple npc name with goal. Each NPC should run one sotopia #109 
- [x] Definition of Scenoria: it should be fixed and generic description about the workspace. The oder of agent should be fixed. The agent_goals order should match the order in code. Ai Agent goals is also fixed. Only change sotopia goals. #108
- [x] Figure out a way to put rocket chat bot username, password #107 
- [x] Multiple NPC configuration. #110
- [x] Seperate into base npc image and npc task example #112

TBD: (We already figure out the feasibility. To avoid over engineering, put it on hold untill we have to do. )
1. NPC can achive more fine-gained control over prompts. 
2. Filter the information source from different user.
3. Prompt Engineer to let NPC only reply the message related to them. Prompt: `You should reply nothing when get message. Unless the message mentions your name`
4. In one channel, we can have one agent and several sotopia NPC. Currently we don't support converstation between sotopia NPC. But can let agent talk with NPC, each NPC can choose reply or not reply.
